version: '3.8'

services:
  app:
    image: ghcr.io/flav-ia/asistente-cupos-back/app:latest
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_AI_OPENAI_API_KEY=${CHATGPT_APIKEY}
      - DATASOURCE_URL=jdbc:mysql://db:${MYSQL_PORT}/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    expose:
      - "3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
