name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  sonar:
    uses: ./.github/workflows/sonar.yml
    needs: build-test

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [ build-test ]
